version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./Solution/DockerCompose/containers/mosquitto/config:/mosquitto/config
      - ./Solution/DockerCompose/data/mosquitto/data:/mosquitto/data
      - ./Solution/DockerCompose/data/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      # - 9001:9001
